(() => {
  const api = MinicampAPI;
  let state;
  const root = document.querySelector(".admin-main");
  function showLogin() {
    if (document.getElementById("admin-login")) return;
    const box=document.createElement("section"); box.id="admin-login"; box.className="admin-login-card";
    box.innerHTML="<p class='section-kicker'>ORGANIZER ACCESS</p><h2>进入主办方工作台</h2><form><label>主办方密码<input type='password' name='password' required></label><p class='form-error'></p><button class='button button-dark'>登录</button></form>";
    root.prepend(box); box.querySelector("form").onsubmit=async e=>{e.preventDefault();try{const d=await api.request("/api/auth/admin",{method:"POST",body:JSON.stringify({password:new FormData(e.currentTarget).get("password")})});api.setToken(d.token);box.remove();await load();}catch(err){box.querySelector(".form-error").textContent=err.message;}};
  }
  async function load(){try{state=await api.request("/api/admin/summary");render();}catch{showLogin();}}
  function render(){const apps=state.applications, accepted=apps.filter(x=>x.status==="已录取").length; document.getElementById("metrics-grid").innerHTML=[["报名总数",apps.length,"服务端数据"],["已录取",accepted,"审核状态"],["已建队伍",state.teams.length,"Team Code"],["已发布项目",state.projects.filter(x=>x.status==="published").length,"Gallery"]].map(x=>"<div class='metric-card'><span>"+x[0]+"</span><strong>"+x[1]+"</strong><small>"+x[2]+"</small></div>").join("");
    document.getElementById("status-bars").innerHTML=["待审核","已录取","候补","待复审"].map(status=>{const count=apps.filter(x=>x.status===status).length;return "<div><div class='status-bar-label'><span>"+status+"</span><b>"+count+"</b></div><div class='status-bar-track'><i style='width:"+(count/Math.max(apps.length,1)*100)+"%'></i></div></div>"}).join("");
    document.getElementById("activity-list").innerHTML=apps.slice(0,5).map(x=>"<div class='activity-item'><span class='activity-dot'>"+x.name.slice(0,1)+"</span><p><strong>"+x.name+"</strong> · "+x.id+"<br><time>"+new Date(x.createdAt).toLocaleString("zh-CN")+"</time></p></div>").join("");
    renderApps(); renderTeams(); renderResults(); renderNotices(); renderConfig(); renderProjects();
  }
  function renderApps(){const tbody=document.getElementById("applicants-table");tbody.innerHTML=state.applications.map(x=>"<tr><td><strong>"+x.name+"</strong><br><small>"+x.college+" · "+x.major+"</small></td><td>"+x.id+"</td><td>"+x.entryType+"</td><td>"+(x.teamIntentName||"—")+"</td><td>"+(x.skills||[]).join(" / ")+"</td><td>"+(x.teamCode||"—")+"</td><td><select class='status-select' data-id='"+x.id+"'>"+["待审核","已录取","候补","待复审"].map(s=>"<option "+(s===x.status?"selected":"")+">"+s+"</option>").join("")+"</select></td><td><button class='row-action' data-view='"+x.id+"'>查看</button></td></tr>").join("");tbody.querySelectorAll(".status-select").forEach(select=>select.onchange=async()=>{await api.request("/api/admin/applications",{method:"PATCH",body:JSON.stringify({id:select.dataset.id,status:select.value})});await load();});tbody.querySelectorAll("[data-view]").forEach(button=>button.onclick=()=>{const x=state.applications.find(item=>item.id===button.dataset.view);alert("申请编号："+x.id+"\n姓名："+x.name+"\n动机："+x.motivation+"\n可帮助："+(x.canHelpWith||"未填写")+"\n想探索："+(x.explore||"未填写"));});}
  function renderTeams(){document.getElementById("team-board").innerHTML=state.teams.map(t=>"<article class='team-card-admin'><div class='team-card-head'><strong>"+t.id+"</strong><span>"+t.members.length+"/5</span></div><p>"+t.project+"</p><small>"+t.code+" · "+(t.locked?"已锁定":"草稿")+"</small><ul>"+t.members.map(m=>"<li>"+m.name+" · "+(m.skills||[]).join(" / ")+"</li>").join("")+"</ul></article>").join("")||"<p>暂无队伍</p>";}
  function renderResults(){const rows=state.results||[];document.getElementById("vote-leader").innerHTML=rows[0]?"<span>"+rows[0].award+" · 当前领先</span><strong>"+rows[0].projectId+"</strong><p>加权分 "+rows[0].weighted+"</p>":"<span>投票结果</span><strong>暂无投票</strong><p>投票开启后显示</p>";document.getElementById("vote-list").innerHTML=rows.map(x=>"<div class='vote-row'><span><b>"+x.award+"</b><br><small>"+x.projectId+"</small></span><div class='vote-meter'><i style='width:"+Math.min(x.weighted,100)+"%'></i></div><strong>"+x.weighted.toFixed(1)+"</strong></div>").join("")||"<p>暂无投票记录</p>";}
  function renderNotices(){const list=document.getElementById("admin-notice-list");list.innerHTML=state.notices.slice(0,10).map(x=>"<article class='admin-notice-item'><div class='notice-meta'><span>"+x.type+"</span><time>"+new Date(x.createdAt).toLocaleString("zh-CN")+"</time></div><h3>"+x.title+"</h3><p>"+x.body+"</p></article>").join("");const target=document.getElementById("notice-target");target.innerHTML="<option value='ALL'>所有报名者</option>"+state.applications.map(x=>"<option value='"+x.id+"'>"+x.name+" · "+x.id+"</option>").join("");}
  function renderConfig(){let box=document.getElementById("config-editor");if(!box){box=document.createElement("section");box.id="config-editor";box.className="admin-card";document.getElementById("panel-overview").append(box);}const c=state.config;box.innerHTML="<div class='admin-card-head'><h2>活动配置</h2><span>服务端实时生效</span></div><form class='field-grid'><label>活动日期<input name='date' value='"+c.date+"'></label><label>报名截止<input type='datetime-local' name='applicationDeadline' value='"+c.applicationDeadline.slice(0,16)+"'></label><label>录取公布<input type='datetime-local' name='resultDate' value='"+c.resultDate.slice(0,16)+"'></label><label>投票开始<input type='datetime-local' name='voteStartAt' value='"+(c.voteStartAt ? c.voteStartAt.slice(0,16) : "")+"'></label><label>报名状态<select name='applicationOpen'><option value='true'>开放</option><option value='false'>关闭</option></select></label><label>参与者权重<input name='participantWeight' type='number' value='"+c.participantWeight+"'></label><label>Jury 权重<input name='juryWeight' type='number' value='"+c.juryWeight+"'></label><button class='button button-dark'>保存配置</button></form>";box.querySelector('[name="applicationOpen"]').value=String(c.applicationOpen);box.querySelector("form").onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));d.applicationOpen=d.applicationOpen==="true";d.voteStartAt=d.voteStartAt||null;d.participantWeight=Number(d.participantWeight);d.juryWeight=Number(d.juryWeight);await api.request("/api/admin/config",{method:"PATCH",body:JSON.stringify(d)});await load();};}
  function renderProjects(){let box=document.getElementById("project-review");if(!box){box=document.createElement("section");box.id="project-review";box.className="admin-card";document.getElementById("panel-overview").append(box);}box.innerHTML="<div class='admin-card-head'><h2>项目审核与发布</h2><span>"+state.projects.length+" 个项目</span></div>"+state.projects.map(p=>"<div class='review-row'><span><b>"+p.projectName+"</b><small>"+p.teamId+" · "+p.status+"</small></span><select data-id='"+p.id+"'><option "+(p.status==="draft"?"selected":"")+">draft</option><option "+(p.status==="published"?"selected":"")+">published</option><option "+(p.status==="archived"?"selected":"")+">archived</option></select></div>").join("");box.querySelectorAll("select").forEach(s=>s.onchange=async()=>{await api.request("/api/admin/projects",{method:"PATCH",body:JSON.stringify({id:s.dataset.id,status:s.value})});await load();});}
  document.getElementById("notice-form")?.addEventListener("submit",async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));await api.request("/api/admin/notices",{method:"POST",body:JSON.stringify(d)});e.currentTarget.reset();await load();});
  document.querySelectorAll(".admin-nav button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".admin-nav button").forEach(x=>x.classList.toggle("active",x===b));document.querySelectorAll(".admin-panel").forEach(x=>x.classList.toggle("active",x.id==="panel-"+b.dataset.panel));});
  load();
})();
