CREATE DATABASE IF NOT EXISTS minicamp2026 CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE minicamp2026;

CREATE TABLE IF NOT EXISTS app_state (
  state_key VARCHAR(64) NOT NULL PRIMARY KEY,
  state_json JSON NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;
