(() => {
  const api=MinicampAPI, awards=["Best Overall","Best Product","Best Design","Best Technical","Most Unexpected"];
  let projects=[], voter, votingOpen=false;
  const login=document.getElementById("voting-login-form"), form=document.getElementById("voting-form");
  function render(){const available=projects.filter(p=>!voter.team||p.teamId!==voter.team.id);document.getElementById("formal-votes").innerHTML=awards.map(a=>"<section class='formal-vote-block'><div class='vote-section-title'><h2>"+a+"</h2><span>第一 3 票 · 第二 2 票 · 第三 1 票</span></div><div class='rank-selects'>"+[3,2,1].map(points=>"<label>"+points+" 票<select data-award='"+a+"' data-points='"+points+"' required><option value=''>请选择</option>"+available.map(p=>"<option value='"+p.id+"'>"+p.projectName+"</option>").join("")+"</select></label>").join("")+"</div></section>").join("");document.getElementById("people-candidates").innerHTML=available.map(p=>"<label class='candidate-card'><input type='radio' name='people-choice' value='"+p.id+"'><strong>"+p.projectName+"</strong><small>"+p.tagline+"</small></label>").join("");}
  api.request("/api/config").then(({config})=>{votingOpen=Boolean(config.voteOpen);if(!votingOpen&&login){const button=login.querySelector("button[type=submit]");if(button)button.disabled=true;const status=document.createElement("p");status.className="vote-closed-status";status.textContent="投票暂未开放，主办方设置开始时间后会自动开放。";login.insertBefore(status,login.querySelector("button"));}}).catch(()=>{});
  login?.addEventListener("submit",async e=>{e.preventDefault();if(!votingOpen){document.getElementById("voter-error").textContent="投票暂未开放。";return;}try{const d=await api.participantLogin(document.getElementById("voter-id").value,document.getElementById("voter-contact").value);voter=d.participant;projects=(await api.request("/api/projects")).projects;document.getElementById("voter-name").textContent=voter.name;document.getElementById("voting-login").hidden=true;document.getElementById("voting-workspace").hidden=false;render();}catch(err){document.getElementById("voter-error").textContent=err.message;}});
  form?.addEventListener("submit",async e=>{e.preventDefault();const selections=[];for(const award of awards){const picks=[...form.querySelectorAll('select[data-award="'+award+'"]')];if(picks.some(x=>!x.value)||new Set(picks.map(x=>x.value)).size<3){document.getElementById("voting-error").textContent="每个奖项请选择三个不同项目。";return;}picks.forEach(p=>selections.push({award,projectId:p.value,points:Number(p.dataset.points)}));}const people=form.querySelector('input[name="people-choice"]:checked');if(!people){document.getElementById("voting-error").textContent="请选择 People's Choice。";return;}selections.push({award:"People's Choice",projectId:people.value,points:1});try{await api.request("/api/votes",{method:"POST",body:JSON.stringify({selections})});document.getElementById("voting-workspace").hidden=true;document.getElementById("vote-success").hidden=false;}catch(err){document.getElementById("voting-error").textContent=err.message;}});
  document.getElementById("voting-logout")?.addEventListener("click",()=>{api.logout();location.reload();});
})();
